import React, { useEffect } from 'react';
import { initPortfolio } from './interactions.js';

export default function App() {
  useEffect(() => {
    const cleanup = initPortfolio();
    import('./vendor/model-viewer.min.js').catch(() => {
      document.getElementById('akhil-model')?.dispatchEvent(new Event('error'));
    });
    return cleanup;
  }, []);
  return (<>

<div id="progress" aria-hidden="true"></div><header><a className="brand" href="#home" aria-label="Akhil home">a<span>.</span></a><nav aria-label="Main navigation"><a href="#story">My story</a><a href="#work">My craft</a><a href="#play">Off duty</a></nav><button id="motion" type="button" aria-pressed="false">Pause motion</button></header>
<main><section id="home" className="hero"><div className="hero-grid" aria-hidden="true"></div><p className="eyebrow hero-eyebrow">AKHIL BENDALAM / VISAKHAPATNAM, INDIA</p><h1>A world<br />of <em>my own.</em></h1><div className="hero-portrait"><div className="halo" aria-hidden="true"></div><img src="assets/hero.png" alt="Akhil Bendalam in a white shirt" width="1024" height="1536" fetchPriority="high" /></div><div className="float-label label-one">&lt; creative developer /&gt;</div><div className="float-label label-two">Made of curiosity.</div><div className="hero-bottom"><p>Developer by profession.<br />Gamer at heart. Always exploring.</p><a className="scroll-link" href="#story">SCROLL TO MEET ME <span aria-hidden="true">↓</span></a><span className="edition">THE PERSONAL EDITION · 01</span></div></section>
<section id="story" className="story"><div className="section-top"><span>01 / THE PERSON</span><span>BEYOND THE SCREEN</span></div><div className="story-layout"><div className="story-stage"><div className="story-visual"><div className="orbit-ring ring-a" aria-hidden="true"></div><div className="orbit-ring ring-b" aria-hidden="true"></div><div className="story-portrait model-stage"><model-viewer id="akhil-model" src="assets/akhil-textured.glb" poster="assets/story.png" alt="A textured three-dimensional model of Akhil in traditional wedding attire. Drag horizontally to rotate; scroll the page to orbit and zoom." camera-controls={true} touch-action="pan-y" disable-pan={true} disable-zoom={true} interaction-prompt="none" camera-orbit="0deg 85deg 115%" min-camera-orbit="auto 40deg 70%" max-camera-orbit="auto 120deg 150%" field-of-view="30deg" shadow-intensity="1" shadow-softness=".8" exposure="1.1" environment-image="neutral" loading="lazy" interpolation-decay="90"><div className="model-loading" slot="poster"><img src="assets/story.png" alt="Akhil portrait while the 3D model loads" /><span>Loading my 3D world…</span></div></model-viewer><div className="model-fallback" hidden={true}><img src="assets/story.png" alt="Akhil in wedding attire" /><p>3D view couldn&#x27;t load on this device.</p><button id="retry-model" type="button">Retry 3D view</button></div></div><span className="portrait-caption">SCROLL TO ORBIT &amp; ZOOM · DRAG TO EXPLORE</span><button id="reset-model" type="button">Reset view</button><div className="portrait-track" aria-hidden="true"><span></span></div></div></div><div className="story-copy"><p className="eyebrow reveal">A LITTLE ABOUT ME</p><h2 className="reveal">Logic in my head.<br /><em>Life in my heart.</em></h2><p className="large-copy reveal">Hey, I&#x27;m Akhil. I turn ideas into interfaces—and keep looking for the next thing to build.</p><p className="muted reveal">Based in Visakhapatnam, I bring around four years of frontend experience to React applications. Outside work, my world has room for games, cinema and a little creative experimentation.</p><div className="mini-facts reveal"><div><strong>Vizag</strong><span>Home base</span></div><div><strong>React</strong><span>My craft</span></div><div><strong>Curiosity</strong><span>My compass</span></div></div></div></div></section>
<div className="marquee" aria-hidden="true"><div>BUILD. PLAY. EXPLORE. REPEAT.   BUILD. PLAY. EXPLORE. REPEAT.  </div></div>
<section id="work" className="work"><div className="section-top"><span>02 / THE CRAFT</span><span>IDEAS INTO INTERFACES</span></div><div className="work-heading"><h2 className="reveal">I build what<br /><em>you interact with.</em></h2><p className="muted reveal">Responsive screens. Reusable components.<br />Thoughtful details that make an app feel right.</p></div><div className="skill-field reveal"><span>React.js</span><span>JavaScript</span><span>Material UI</span><span>Redux</span><span>TypeScript</span><span>REST APIs</span><span className="learning">Exploring GenAI + RAG</span></div><div className="projects"><article className="project reveal"><div className="project-art chat-art" aria-hidden="true"><div className="mock-bar"><i></i><i></i><i></i><span>AI FACT GPT</span></div><div className="mock-question">A question becomes a conversation.</div><div className="mock-answer"><b>AI</b><div><span></span><span></span><span></span></div></div><div className="mock-input">Ask. Explore. Understand.</div></div><div className="project-info"><span>01 / CONVERSATIONAL UI</span><h3>AI Fact GPT</h3><p>React and MUI interfaces for an AI-driven chatbot, with a focus on usability and frontend performance.</p><small>REACT · MUI · ENTERPRISE UI</small></div></article><article className="project reveal"><div className="project-art dash-art" aria-hidden="true"><div className="mock-bar"><i></i><i></i><i></i><span>DTC ANALYTICS</span></div><div className="metric-row"><div>Signals<br /><b>Overview</b></div><div>Analytics<br /><b>Insights</b></div></div><div className="chart"><i style={{"--bar": "35%"}}></i><i style={{"--bar": "60%"}}></i><i style={{"--bar": "45%"}}></i><i style={{"--bar": "80%"}}></i><i style={{"--bar": "58%"}}></i><i style={{"--bar": "95%"}}></i><i style={{"--bar": "75%"}}></i></div></div><div className="project-info"><span>02 / DATA &amp; DASHBOARDS</span><h3>RESS &amp; DTC</h3><p>Dashboards, charts and analytical views for General Motors applications. Turning complex data into clear screens.</p><small>REACT · DATA VISUALIZATION · REST APIs</small></div></article></div><div className="chapter-note reveal"><span>WHAT&#x27;S NEXT?</span><p>Exploring GenAI, RAG and the possibilities of intelligent interfaces.</p><span className="asterisk" aria-hidden="true">✳</span></div></section>
<section id="play" className="play"><div className="section-top"><span>03 / OFF DUTY</span><span>A DIFFERENT KIND OF ENERGY</span></div><div className="gaming-scene"><div className="target-ring" aria-hidden="true"></div><div className="gaming-title"><p className="eyebrow">WHEN THE CODE CAN WAIT</p><h2>Game<br /><em>mode: on.</em></h2><p>New worlds. Good competition.<br />One more round.</p></div><div className="game-orbit" aria-hidden="true"><div className="game-object controller"><div></div></div><div className="game-object console"><div></div></div><div className="game-object rifle"><div></div></div><div className="game-object helmet"><div></div></div></div><span className="scene-caption">GAMING / PUBG / CONSOLE WORLDS</span></div><div className="interests"><article className="reveal"><span>01</span><h3>The big screen.</h3><p>From Mahesh Babu and Allu Arjun to a film worth discovering. Cinema is another world to get lost in.</p><div className="film-strip" aria-hidden="true">ACTION   STORIES   CINEMA</div></article><article className="reveal"><span>02</span><h3>The next idea.</h3><p>Multiplayer games. AI conversations. Small experiments that start with “what if?” and become something real.</p><div className="idea-mark" aria-hidden="true">WHAT IF<span>?</span></div></article></div></section>
<section className="closing"><p className="eyebrow reveal">ONE PERSON. MANY POSSIBILITIES.</p><h2 className="reveal">Still curious.<br /><em>Still creating.</em></h2><p className="muted reveal">That&#x27;s a little of my world. Thanks for stepping into it.</p><a className="back-top" href="#home">Back to the beginning</a></section></main><footer><a className="brand" href="#home">a<span>.</span></a><p>AKHIL BENDALAM</p><span>MADE WITH CURIOSITY · VIZAG</span></footer>
  </>);
}
